In [1]:
import pandas as pd
import numpy as np
from tensorflow import keras

In [2]:
name = "ICU Mortality Prediction"

## Inputting Our Data

In [3]:
path = "./data/train_x.csv"
# dtypes = {"admissionheight": float, "admissionweight": float, "age": str, "gender": str, "nursingchartcelltypevalname": str, "nursingchartvalue": float, "offset": int, "patientunitstayid": int, "unitvisitnumber": int }
df = pd.read_csv(path, dtype=str, keep_default_na=False, na_values=[""], engine="python")
print("Reading data from: {}".format(path))

Reading data from: ./data/train_x.csv

## Preprocessing

In [4]:
df.rename(columns={df.columns[0]: "id"}, inplace=True)
df.drop("cellattributevalue", axis=1, inplace=True)
df.drop("celllabel", axis=1, inplace=True)
df.drop("labmeasurenamesystem", axis=1, inplace=True)
df.drop("labname", axis=1, inplace=True)
df.drop("labresult", axis=1, inplace=True)

In [5]:
df["id"] = df["id"].astype("int64")
df["admissionheight"] = df["admissionheight"].astype(float)
df["admissionweight"] = df["admissionweight"].astype(float)
df.replace(["> 89"], 90, inplace=True)
df["age"] = df["age"].astype(float)
df["gender"] = df["gender"].astype(str)
df["ethnicity"] = df["ethnicity"].astype(str)
df["nursingchartcelltypevalname"] = df["nursingchartcelltypevalname"].astype(str)
df.replace(["Unable to score due to medication"], np.nan, inplace=True)
df["nursingchartvalue"] = df["nursingchartvalue"].astype(float)
df["offset"] = df["offset"].astype(float)
df["patientunitstayid"] = df["patientunitstayid"].astype(float)
df["unitvisitnumber"] = df["unitvisitnumber"].astype(float)
df.shape, df.dtypes

((791936, 11),
 id                               int64
 admissionheight                float64
 admissionweight                float64
 age                            float64
 ethnicity                       object
 gender                          object
 nursingchartcelltypevalname     object
 nursingchartvalue              float64
 offset                         float64
 patientunitstayid              float64
 unitvisitnumber                float64
 dtype: object)

In [7]:
nonnumerical = df.select_dtypes(exclude=["int64", "float64"])
categorical = pd.get_dummies(nonnumerical)
numerical =  df.select_dtypes(include=["int64", "float64"])
final_features = pd.concat([numerical, categorical], axis=1)

In [8]:
labels = pd.read_csv("./data/train_y.csv", dtype=str, keep_default_na=False, na_values=[""], engine="python")

In [9]:
# import os  
# df.to_csv("./data/filtered.csv")  
# features.to_csv("./data/pivoted.csv")

## Analyzing Dataset

In [10]:
display(final_features)
display(final_features.describe().T)

,id,admissionheight,admissionweight,age,nursingchartvalue,offset,patientunitstayid,unitvisitnumber,ethnicity_African American,ethnicity_Asian,...,nursingchartcelltypevalname_Heart Rate,nursingchartcelltypevalname_Invasive BP Diastolic,nursingchartcelltypevalname_Invasive BP Mean,nursingchartcelltypevalname_Invasive BP Systolic,nursingchartcelltypevalname_Non-Invasive BP Diastolic,nursingchartcelltypevalname_Non-Invasive BP Mean,nursingchartcelltypevalname_Non-Invasive BP Systolic,nursingchartcelltypevalname_O2 Saturation,nursingchartcelltypevalname_Respiratory Rate,nursingchartcelltypevalname_nan
0,0,157.5,NaN,87.0,NaN,0.0,141764.0,2.0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,1,157.5,46.5,87.0,NaN,0.0,141765.0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,2,167.0,77.5,76.0,NaN,0.0,143870.0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,3,172.7,60.3,34.0,NaN,0.0,144815.0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,4,177.8,91.7,61.0,NaN,0.0,145427.0,1.0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
791931,791931,NaN,NaN,NaN,NaN,931.0,2715137.0,NaN,0,0,...,0,0,0,0,0,0,0,0,0,1
791932,791932,NaN,NaN,NaN,NaN,1951.0,2715137.0,NaN,0,0,...,0,0,0,0,0,0,0,0,0,1
791933,791933,NaN,NaN,NaN,NaN,1001.0,2715137.0,NaN,0,0,...,0,0,0,0,0,0,0,0,0,1
791934,791934,NaN,NaN,NaN,NaN,37.0,2754778.0,NaN,0,0,...,0,0,0,0,0,0,0,0,0,1
791935,791935,NaN,NaN,NaN,NaN,1282.0,2754778.0,NaN,0,0,...,0,0,0,0,0,0,0,0,0,1

,count,mean,std,min,25%,50%,75%,max
id,791936.0,3.959675e+05,2.286124e+05,0.0,197983.75,395967.50,593951.250,791935.0
admissionheight,1957.0,1.699399e+02,1.662301e+01,0.3,162.60,170.20,177.800,600.0
admissionweight,1856.0,8.268857e+01,2.435354e+01,0.5,65.70,78.91,96.125,227.7
age,2012.0,6.329523e+01,1.767290e+01,15.0,53.00,66.00,77.000,90.0
nursingchartvalue,773272.0,7.684195e+01,3.765256e+01,-90.0,55.00,81.00,99.000,1114.0
offset,791936.0,5.107248e+03,8.347077e+03,-68394.0,646.00,2217.00,5893.000,76852.0
patientunitstayid,791936.0,1.784650e+06,1.019373e+06,141764.0,931649.00,1705630.00,2755766.000,3353113.0
unitvisitnumber,2016.0,1.198909e+00,5.163518e-01,1.0,1.00,1.00,1.000,5.0
ethnicity_African American,791936.0,2.348675e-04,1.532360e-02,0.0,0.00,0.00,0.000,1.0
ethnicity_Asian,791936.0,2.651729e-05,5.149430e-03,0.0,0.00,0.00,0.000,1.0
ethnicity_Caucasian,791936.0,2.022891e-03,4.493107e-02,0.0,0.00,0.00,0.000,1.0
ethnicity_Hispanic,791936.0,1.136455e-04,1.065987e-02,0.0,0.00,0.00,0.000,1.0
ethnicity_Native American,791936.0,1.515274e-05,3.892625e-03,0.0,0.00,0.00,0.000,1.0
ethnicity_Other/Unknown,791936.0,8.712825e-05,9.333851e-03,0.0,0.00,0.00,0.000,1.0
ethnicity_nan,791936.0,9.974998e-01,4.993951e-02,0.0,1.00,1.00,1.000,1.0
gender_Female,791936.0,1.007657e-03,3.172764e-02,0.0,0.00,0.00,0.000,1.0
gender_Male,791936.0,1.532952e-03,3.912294e-02,0.0,0.00,0.00,0.000,1.0
gender_nan,791936.0,9.974594e-01,5.034042e-02,0.0,1.00,1.00,1.000,1.0
nursingchartcelltypevalname_GCS Total,791936.0,2.654255e-02,1.607423e-01,0.0,0.00,0.00,0.000,1.0
nursingchartcelltypevalname_Heart Rate,791936.0,1.762491e-01,3.810322e-01,0.0,0.00,0.00,0.000,1.0
nursingchartcelltypevalname_Invasive BP Diastolic,791936.0,2.571925e-02,1.582966e-01,0.0,0.00,0.00,0.000,1.0
nursingchartcelltypevalname_Invasive BP Mean,791936.0,2.295514e-02,1.497606e-01,0.0,0.00,0.00,0.000,1.0
nursingchartcelltypevalname_Invasive BP Systolic,791936.0,2.572051e-02,1.583003e-01,0.0,0.00,0.00,0.000,1.0
nursingchartcelltypevalname_Non-Invasive BP Diastolic,791936.0,1.438210e-01,3.509083e-01,0.0,0.00,0.00,0.000,1.0
nursingchartcelltypevalname_Non-Invasive BP Mean,791936.0,1.150573e-01,3.190913e-01,0.0,0.00,0.00,0.000,1.0
nursingchartcelltypevalname_Non-Invasive BP Systolic,791936.0,1.438184e-01,3.509058e-01,0.0,0.00,0.00,0.000,1.0
nursingchartcelltypevalname_O2 Saturation,791936.0,1.305585e-01,3.369171e-01,0.0,0.00,0.00,0.000,1.0
nursingchartcelltypevalname_Respiratory Rate,791936.0,1.665728e-01,3.725943e-01,0.0,0.00,0.00,0.000,1.0
nursingchartcelltypevalname_nan,791936.0,2.298544e-02,1.498571e-01,0.0,0.00,0.00,0.000,1.0

In [11]:
corr = final_features.corr() 
corr.style.background_gradient(cmap='coolwarm')

## Splitting Our Data

In [13]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, train_size=.8, random_state=42)

NameError: name 'x' is not defined